package stuba.bpbphibernatemapper;
// Generated 26-Mar-2015 03:57:15 by Hibernate Tools 3.6.0



/**
 * GtfsCalendarDates generated by hbm2java
 */
public class GtfsCalendarDates  implements java.io.Serializable {


     private Integer gid;
     private String date;
     private Integer exceptionType;
     private String serviceIdAgencyId;
     private String serviceIdId;

    public GtfsCalendarDates() {
    }

    public GtfsCalendarDates(String date, Integer exceptionType, String serviceIdAgencyId, String serviceIdId) {
       this.date = date;
       this.exceptionType = exceptionType;
       this.serviceIdAgencyId = serviceIdAgencyId;
       this.serviceIdId = serviceIdId;
    }
   
    public Integer getGid() {
        return this.gid;
    }
    
    public void setGid(Integer gid) {
        this.gid = gid;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public Integer getExceptionType() {
        return this.exceptionType;
    }
    
    public void setExceptionType(Integer exceptionType) {
        this.exceptionType = exceptionType;
    }
    public String getServiceIdAgencyId() {
        return this.serviceIdAgencyId;
    }
    
    public void setServiceIdAgencyId(String serviceIdAgencyId) {
        this.serviceIdAgencyId = serviceIdAgencyId;
    }
    public String getServiceIdId() {
        return this.serviceIdId;
    }
    
    public void setServiceIdId(String serviceIdId) {
        this.serviceIdId = serviceIdId;
    }




}


