package stuba.bpbphibernatemapper;
// Generated 26-Mar-2015 03:57:15 by Hibernate Tools 3.6.0



/**
 * GtfsRoutesId generated by hbm2java
 */
public class GtfsRoutesId  implements java.io.Serializable {


     private String agencyId;
     private String id;

    public GtfsRoutesId() {
    }

    public GtfsRoutesId(String agencyId, String id) {
       this.agencyId = agencyId;
       this.id = id;
    }
   
    public String getAgencyId() {
        return this.agencyId;
    }
    
    public void setAgencyId(String agencyId) {
        this.agencyId = agencyId;
    }
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GtfsRoutesId) ) return false;
		 GtfsRoutesId castOther = ( GtfsRoutesId ) other; 
         
		 return ( (this.getAgencyId()==castOther.getAgencyId()) || ( this.getAgencyId()!=null && castOther.getAgencyId()!=null && this.getAgencyId().equals(castOther.getAgencyId()) ) )
 && ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAgencyId() == null ? 0 : this.getAgencyId().hashCode() );
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         return result;
   }   


}


