package stuba.bpbphibernatemapper;
// Generated 26-Mar-2015 03:57:15 by Hibernate Tools 3.6.0



/**
 * GtfsCalendars generated by hbm2java
 */
public class GtfsCalendars  implements java.io.Serializable {


     private Integer gid;
     private Integer monday;
     private Integer tuesday;
     private Integer wednesday;
     private Integer thursday;
     private Integer friday;
     private Integer saturday;
     private Integer sunday;
     private String startDate;
     private String endDate;
     private String serviceIdAgencyId;
     private String serviceIdId;

    public GtfsCalendars() {
    }

    public GtfsCalendars(Integer monday, Integer tuesday, Integer wednesday, Integer thursday, Integer friday, Integer saturday, Integer sunday, String startDate, String endDate, String serviceIdAgencyId, String serviceIdId) {
       this.monday = monday;
       this.tuesday = tuesday;
       this.wednesday = wednesday;
       this.thursday = thursday;
       this.friday = friday;
       this.saturday = saturday;
       this.sunday = sunday;
       this.startDate = startDate;
       this.endDate = endDate;
       this.serviceIdAgencyId = serviceIdAgencyId;
       this.serviceIdId = serviceIdId;
    }
   
    public Integer getGid() {
        return this.gid;
    }
    
    public void setGid(Integer gid) {
        this.gid = gid;
    }
    public Integer getMonday() {
        return this.monday;
    }
    
    public void setMonday(Integer monday) {
        this.monday = monday;
    }
    public Integer getTuesday() {
        return this.tuesday;
    }
    
    public void setTuesday(Integer tuesday) {
        this.tuesday = tuesday;
    }
    public Integer getWednesday() {
        return this.wednesday;
    }
    
    public void setWednesday(Integer wednesday) {
        this.wednesday = wednesday;
    }
    public Integer getThursday() {
        return this.thursday;
    }
    
    public void setThursday(Integer thursday) {
        this.thursday = thursday;
    }
    public Integer getFriday() {
        return this.friday;
    }
    
    public void setFriday(Integer friday) {
        this.friday = friday;
    }
    public Integer getSaturday() {
        return this.saturday;
    }
    
    public void setSaturday(Integer saturday) {
        this.saturday = saturday;
    }
    public Integer getSunday() {
        return this.sunday;
    }
    
    public void setSunday(Integer sunday) {
        this.sunday = sunday;
    }
    public String getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }
    public String getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }
    public String getServiceIdAgencyId() {
        return this.serviceIdAgencyId;
    }
    
    public void setServiceIdAgencyId(String serviceIdAgencyId) {
        this.serviceIdAgencyId = serviceIdAgencyId;
    }
    public String getServiceIdId() {
        return this.serviceIdId;
    }
    
    public void setServiceIdId(String serviceIdId) {
        this.serviceIdId = serviceIdId;
    }




}


