package stuba.bpbphibernatemapper;
// Generated 26-Mar-2015 03:57:15 by Hibernate Tools 3.6.0



/**
 * GtfsStopTimes generated by hbm2java
 */
public class GtfsStopTimes  implements java.io.Serializable {


     private Integer gid;
     private GtfsStops gtfsStops;
     private GtfsTrips gtfsTrips;
     private Integer stopSequence;
     private Integer arrivalTime;
     private Integer departureTime;
     private Integer timepoint;
     private String stopHeadsign;
     private String routeShortName;
     private Integer pickupType;
     private Integer dropOffType;
     private Double shapeDistTraveled;

    public GtfsStopTimes() {
    }

    public GtfsStopTimes(GtfsStops gtfsStops, GtfsTrips gtfsTrips, Integer stopSequence, Integer arrivalTime, Integer departureTime, Integer timepoint, String stopHeadsign, String routeShortName, Integer pickupType, Integer dropOffType, Double shapeDistTraveled) {
       this.gtfsStops = gtfsStops;
       this.gtfsTrips = gtfsTrips;
       this.stopSequence = stopSequence;
       this.arrivalTime = arrivalTime;
       this.departureTime = departureTime;
       this.timepoint = timepoint;
       this.stopHeadsign = stopHeadsign;
       this.routeShortName = routeShortName;
       this.pickupType = pickupType;
       this.dropOffType = dropOffType;
       this.shapeDistTraveled = shapeDistTraveled;
    }
   
    public Integer getGid() {
        return this.gid;
    }
    
    public void setGid(Integer gid) {
        this.gid = gid;
    }
    public GtfsStops getGtfsStops() {
        return this.gtfsStops;
    }
    
    public void setGtfsStops(GtfsStops gtfsStops) {
        this.gtfsStops = gtfsStops;
    }
    public GtfsTrips getGtfsTrips() {
        return this.gtfsTrips;
    }
    
    public void setGtfsTrips(GtfsTrips gtfsTrips) {
        this.gtfsTrips = gtfsTrips;
    }
    public Integer getStopSequence() {
        return this.stopSequence;
    }
    
    public void setStopSequence(Integer stopSequence) {
        this.stopSequence = stopSequence;
    }
    public Integer getArrivalTime() {
        return this.arrivalTime;
    }
    
    public void setArrivalTime(Integer arrivalTime) {
        this.arrivalTime = arrivalTime;
    }
    public Integer getDepartureTime() {
        return this.departureTime;
    }
    
    public void setDepartureTime(Integer departureTime) {
        this.departureTime = departureTime;
    }
    public Integer getTimepoint() {
        return this.timepoint;
    }
    
    public void setTimepoint(Integer timepoint) {
        this.timepoint = timepoint;
    }
    public String getStopHeadsign() {
        return this.stopHeadsign;
    }
    
    public void setStopHeadsign(String stopHeadsign) {
        this.stopHeadsign = stopHeadsign;
    }
    public String getRouteShortName() {
        return this.routeShortName;
    }
    
    public void setRouteShortName(String routeShortName) {
        this.routeShortName = routeShortName;
    }
    public Integer getPickupType() {
        return this.pickupType;
    }
    
    public void setPickupType(Integer pickupType) {
        this.pickupType = pickupType;
    }
    public Integer getDropOffType() {
        return this.dropOffType;
    }
    
    public void setDropOffType(Integer dropOffType) {
        this.dropOffType = dropOffType;
    }
    public Double getShapeDistTraveled() {
        return this.shapeDistTraveled;
    }
    
    public void setShapeDistTraveled(Double shapeDistTraveled) {
        this.shapeDistTraveled = shapeDistTraveled;
    }




}


