package stuba.bpbphibernatemapper;
// Generated 26-Mar-2015 03:57:15 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * GtfsStops generated by hbm2java
 */
public class GtfsStops  implements java.io.Serializable {


     private GtfsStopsId id;
     private String code;
     private String name;
     private String description;
     private String direction;
     private Double lat;
     private Double lon;
     private String zoneId;
     private String url;
     private Integer locationType;
     private String parentStation;
     private String timezone;
     private Integer vehicleType;
     private Integer wheelchairBoarding;
     private String platformCode;
     private Set gtfsStopTimeses = new HashSet(0);

    public GtfsStops() {
    }

	
    public GtfsStops(GtfsStopsId id) {
        this.id = id;
    }
    public GtfsStops(GtfsStopsId id, String code, String name, String description, String direction, Double lat, Double lon, String zoneId, String url, Integer locationType, String parentStation, String timezone, Integer vehicleType, Integer wheelchairBoarding, String platformCode, Set gtfsStopTimeses) {
       this.id = id;
       this.code = code;
       this.name = name;
       this.description = description;
       this.direction = direction;
       this.lat = lat;
       this.lon = lon;
       this.zoneId = zoneId;
       this.url = url;
       this.locationType = locationType;
       this.parentStation = parentStation;
       this.timezone = timezone;
       this.vehicleType = vehicleType;
       this.wheelchairBoarding = wheelchairBoarding;
       this.platformCode = platformCode;
       this.gtfsStopTimeses = gtfsStopTimeses;
    }
   
    public GtfsStopsId getId() {
        return this.id;
    }
    
    public void setId(GtfsStopsId id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getDirection() {
        return this.direction;
    }
    
    public void setDirection(String direction) {
        this.direction = direction;
    }
    public Double getLat() {
        return this.lat;
    }
    
    public void setLat(Double lat) {
        this.lat = lat;
    }
    public Double getLon() {
        return this.lon;
    }
    
    public void setLon(Double lon) {
        this.lon = lon;
    }
    public String getZoneId() {
        return this.zoneId;
    }
    
    public void setZoneId(String zoneId) {
        this.zoneId = zoneId;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Integer getLocationType() {
        return this.locationType;
    }
    
    public void setLocationType(Integer locationType) {
        this.locationType = locationType;
    }
    public String getParentStation() {
        return this.parentStation;
    }
    
    public void setParentStation(String parentStation) {
        this.parentStation = parentStation;
    }
    public String getTimezone() {
        return this.timezone;
    }
    
    public void setTimezone(String timezone) {
        this.timezone = timezone;
    }
    public Integer getVehicleType() {
        return this.vehicleType;
    }
    
    public void setVehicleType(Integer vehicleType) {
        this.vehicleType = vehicleType;
    }
    public Integer getWheelchairBoarding() {
        return this.wheelchairBoarding;
    }
    
    public void setWheelchairBoarding(Integer wheelchairBoarding) {
        this.wheelchairBoarding = wheelchairBoarding;
    }
    public String getPlatformCode() {
        return this.platformCode;
    }
    
    public void setPlatformCode(String platformCode) {
        this.platformCode = platformCode;
    }
    public Set getGtfsStopTimeses() {
        return this.gtfsStopTimeses;
    }
    
    public void setGtfsStopTimeses(Set gtfsStopTimeses) {
        this.gtfsStopTimeses = gtfsStopTimeses;
    }




}


