package stuba.bpbphibernatemapper;
// Generated 26-Mar-2015 03:57:15 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * GtfsRoutes generated by hbm2java
 */
public class GtfsRoutes  implements java.io.Serializable {


     private GtfsRoutesId id;
     private GtfsAgencies gtfsAgencies;
     private String description;
     private String shortName;
     private String longName;
     private Integer type;
     private String url;
     private String color;
     private String textColor;
     private Set gtfsTripses = new HashSet(0);
     private Set poisInRouteses = new HashSet(0);

    public GtfsRoutes() {
    }

	
    public GtfsRoutes(GtfsRoutesId id, GtfsAgencies gtfsAgencies) {
        this.id = id;
        this.gtfsAgencies = gtfsAgencies;
    }
    public GtfsRoutes(GtfsRoutesId id, GtfsAgencies gtfsAgencies, String description, String shortName, String longName, Integer type, String url, String color, String textColor, Set gtfsTripses, Set poisInRouteses) {
       this.id = id;
       this.gtfsAgencies = gtfsAgencies;
       this.description = description;
       this.shortName = shortName;
       this.longName = longName;
       this.type = type;
       this.url = url;
       this.color = color;
       this.textColor = textColor;
       this.gtfsTripses = gtfsTripses;
       this.poisInRouteses = poisInRouteses;
    }
   
    public GtfsRoutesId getId() {
        return this.id;
    }
    
    public void setId(GtfsRoutesId id) {
        this.id = id;
    }
    public GtfsAgencies getGtfsAgencies() {
        return this.gtfsAgencies;
    }
    
    public void setGtfsAgencies(GtfsAgencies gtfsAgencies) {
        this.gtfsAgencies = gtfsAgencies;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getShortName() {
        return this.shortName;
    }
    
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }
    public String getLongName() {
        return this.longName;
    }
    
    public void setLongName(String longName) {
        this.longName = longName;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getTextColor() {
        return this.textColor;
    }
    
    public void setTextColor(String textColor) {
        this.textColor = textColor;
    }
    public Set getGtfsTripses() {
        return this.gtfsTripses;
    }
    
    public void setGtfsTripses(Set gtfsTripses) {
        this.gtfsTripses = gtfsTripses;
    }
    public Set getPoisInRouteses() {
        return this.poisInRouteses;
    }
    
    public void setPoisInRouteses(Set poisInRouteses) {
        this.poisInRouteses = poisInRouteses;
    }




}


