package stuba.bpbphibernatemapper;
// Generated 26-Mar-2015 03:57:15 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Poi generated by hbm2java
 */
public class Poi  implements java.io.Serializable {


     private Long id;
     private float lat;
     private float lon;
     private float radius;
     private String title;
     private String filePath;
     private Date createdAt;
     private Set poisInRouteses = new HashSet(0);

    public Poi() {
    }

	
    public Poi(float lat, float lon, float radius, String title, String filePath) {
        this.lat = lat;
        this.lon = lon;
        this.radius = radius;
        this.title = title;
        this.filePath = filePath;
    }
    public Poi(float lat, float lon, float radius, String title, String filePath, Date createdAt, Set poisInRouteses) {
       this.lat = lat;
       this.lon = lon;
       this.radius = radius;
       this.title = title;
       this.filePath = filePath;
       this.createdAt = createdAt;
       this.poisInRouteses = poisInRouteses;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public float getLat() {
        return this.lat;
    }
    
    public void setLat(float lat) {
        this.lat = lat;
    }
    public float getLon() {
        return this.lon;
    }
    
    public void setLon(float lon) {
        this.lon = lon;
    }
    public float getRadius() {
        return this.radius;
    }
    
    public void setRadius(float radius) {
        this.radius = radius;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getFilePath() {
        return this.filePath;
    }
    
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Set getPoisInRouteses() {
        return this.poisInRouteses;
    }
    
    public void setPoisInRouteses(Set poisInRouteses) {
        this.poisInRouteses = poisInRouteses;
    }




}


