package stuba.bpbphibernatemapper;
// Generated 26-Mar-2015 03:57:15 by Hibernate Tools 3.6.0



/**
 * PoisInRoutes generated by hbm2java
 */
public class PoisInRoutes  implements java.io.Serializable {


     private Long id;
     private Poi poi;
     private GtfsRoutes gtfsRoutes;

    public PoisInRoutes() {
    }

    public PoisInRoutes(Poi poi, GtfsRoutes gtfsRoutes) {
       this.poi = poi;
       this.gtfsRoutes = gtfsRoutes;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Poi getPoi() {
        return this.poi;
    }
    
    public void setPoi(Poi poi) {
        this.poi = poi;
    }
    public GtfsRoutes getGtfsRoutes() {
        return this.gtfsRoutes;
    }
    
    public void setGtfsRoutes(GtfsRoutes gtfsRoutes) {
        this.gtfsRoutes = gtfsRoutes;
    }




}


