package stuba.bpbphibernatemapper;
// Generated 26-Mar-2015 03:57:15 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * TripPositions generated by hbm2java
 */
public class TripPositions  implements java.io.Serializable {


     private Long id;
     private GtfsTrips gtfsTrips;
     private double lat;
     private double lon;
     private int delay;
     private double speed;
     private double accuracy;
     private Date createdAt;

    public TripPositions() {
    }
    
    public TripPositions(GtfsTrips gtfsTrips, double lat, double lon, int delay, double speed, double accuracy) {
       this.gtfsTrips = gtfsTrips;
       this.lat = lat;
       this.lon = lon;
       this.delay = delay;
       this.speed = speed;
       this.accuracy = accuracy;
    }

    public TripPositions(GtfsTrips gtfsTrips, double lat, double lon, int delay, double speed, double accuracy, Date createdAt) {
       this.gtfsTrips = gtfsTrips;
       this.lat = lat;
       this.lon = lon;
       this.delay = delay;
       this.speed = speed;
       this.accuracy = accuracy;
       this.createdAt = createdAt;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public GtfsTrips getGtfsTrips() {
        return this.gtfsTrips;
    }
    
    public void setGtfsTrips(GtfsTrips gtfsTrips) {
        this.gtfsTrips = gtfsTrips;
    }
    public double getLat() {
        return this.lat;
    }
    
    public void setLat(double lat) {
        this.lat = lat;
    }
    public double getLon() {
        return this.lon;
    }
    
    public void setLon(double lon) {
        this.lon = lon;
    }
    public int getDelay() {
        return this.delay;
    }
    
    public void setDelay(int delay) {
        this.delay = delay;
    }
    public double getSpeed() {
        return this.speed;
    }
    
    public void setSpeed(double speed) {
        this.speed = speed;
    }
    public double getAccuracy() {
        return this.accuracy;
    }
    
    public void setAccuracy(double accuracy) {
        this.accuracy = accuracy;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }




}


